[control_plane]
master ansible_host=192.168.122.10 ansible_user=master ansible_become_pass=root

[workers]
w1 ansible_host=192.168.122.11 ansible_user=w1 ansible_become_pass=root
w2 ansible_host=192.168.122.12 ansible_user=w2 ansible_become_pass=root

[k8s:children]
control_plane
workers

[k8s:vars]
ansible_ssh_private_key_file=/home/natnaelae/.ssh/id_ed25519
ansible_ssh_common_args='-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null'

ansible_become=yes
ansible_become_method=sudo
ansible_become_user=root
